### ISSUE TITLE
predef imports not visible in notebook

### ISSUE THREAD

**Issue by jameskoch2** [almond-sh/almond#218]
Using: 0.1.5

Modify kernel.json to add:
```
    "--predef",
    "import scala.collection.JavaConverters",
```

Launch kernel and evaluate a cell containing only `JavaConverters` and see error:
```
cmd1.sc:1: not found: value JavaConverters
val res1 = JavaConverters
           ^Compilation Failed
```

I suspect this is related to the predefs being pushed through as "warm ups".

Related evidence, when no --predef is passed, the dummy `array` symbol [created here](https://github.com/jupyter-scala/jupyter-scala/blob/develop/modules/scala/scala-interpreter/src/main/scala/almond/ScalaInterpreter.scala#L284-L289) is similarly not visible in the notebook (obviously desirable in the case of a pure warm-up statement).

**Comment by alexarchambault** [comment]
https://github.com/almond-sh/almond/pull/217 fixed that it seems. (This works fine in `0.1.8`.)

**Comment by jameskoch** [comment]
Yes, works fine over here now.  Thank you!
